name: Maven Publish

on:
  push:
    branches:
      - main
jobs:
  publish-central:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Git Repo
        uses: actions/checkout@v4

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'      # 一般只需要修改这里，8 17 21 等等
          server-id: absorprofess
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to Apache Maven Central
        run: mvn deploy
        env:
          SERVER_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}