name: Maven Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure Maven Settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>absorprofess</id><username>${{ secrets.OSSRH_USERNAME }}</username><password>${{ secrets.OSSRH_PASSWORD }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Install GPG Key
        run: |
          echo "${{ secrets.GPG_KEY }}" | gpg --batch --import
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}

      - name: Publish to Sonatype
        run: mvn clean deploy -P release -DskipTests
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}